/********************************************************************************************************************
@Author:Rajesh Kumar(LTIMindtree)
@Description: This class is reasponsilbe for sharing the related list of Manufacture Account related records with the 
associated dealer user.
@User Story:DP-1241
@Created Date:October-15-2024 	    
*********************************************************************************************************************/
public Without sharing class PEAC_ManufacturerShareQueueable{
   public static void emptyMethod()
   {
     //empty method 
   }
}