/********************************************************************************************************************
@Author:Rajesh Kumar(LTIMindtree)
@Description: This class is reasponsilbe for sharing the related list of Manufacture Account related records with the 
            associated dealer user.
@User Story:DP-1241
@Created Date:October-14-2024 	    
*********************************************************************************************************************/
public with sharing class PEAC_ManufacturerSharingClass {

   public static void emptyMethod()
   {
     //empty method 
   }
}