public without sharing class SL_UpdateTasks {
    /**
    * Summary:       Receives a list of tasks and updates them, the class was created to use a different sharing model
    * Inputs:        taskList - list of tasks to be updated
    * Returns:       void
    * Author:        Paul Trujillo 
    * Company:       Irvine Company
    * Created:       10/23/2024
    * History
    * <Date>        <Authors Name>          <Jira#>      <Brief Description of Change>
    * 02/04/2024    Paul Trujillo           SL-2504         Initial version.
    */
    public static void updateTasks(List<Task> taskList) {
        update taskList;
    }
}