@isTest
public class TC_DocuSignRecipientStatusTest {
    
      
     //// Start: Test class to cover codcoverage for decommision(SAL-4149) class-By Raja Sirivella
   static testmethod void test134545(){
        Test.startTest();

       TC_DocusignRecipientStatusTriggerHelper cs = new TC_DocusignRecipientStatusTriggerHelper();
       cs.TC_DocusignRecipientStatusTriggerHelper('test');

        Test.stopTest();
    }
    
      //// Start: Test class to cover codcoverage for decommision(SAL-4149) class-By Raja Sirivella
   static testmethod void test13456(){
        Test.startTest();

       TC_SetDocusignRecipientContact cs = new TC_SetDocusignRecipientContact();
       cs.TC_SetDocusignRecipientContact('test');

        Test.stopTest();
    }
}